require('@rails/ujs').start()
require('turbolinks').start()
require('@rails/activestorage').start()
require('channels')
require('bootstrap')
require('admin-lte')
require('@fortawesome/fontawesome-free')
global.$ = global.jQuery = require('jquery')
global.I18n = require('i18n-js')
